### ISSUE TITLE
Verify OMPL works with continuous joints

### ISSUE THREAD

**Issue by mklingen** [personalrobotics/or_ompl#20]
In simulation, OMPL seems to produce good trajectories for ADA, but this could just be a happy accident because of the starting configuration of the robot being inside -pi to +pi. Does the OMPL planner work properly with toroidal or other continuous spaces? I believe there is a way to make it do this properly, but or_ompl needs to do it as well.

**Comment by siddhss5** [comment]
This is what @mkoval suggested on Slack:
I suggest constructing one `StateSpace` per DOF. create a 1-DOF `RealVectorStateSpace` if the DOF is not circular. create an `SO2StateSpace` if the DOF is circular.
I implemented that in DART and it's pretty straightforward: https://github.com/personalrobotics/r3/blob/master/src/ompl/DARTGeometricStateSpace.cpp#L19

**Comment by mklingen** [comment]
Some updates on this. @Stefanos19 apparently made a branch on this (continuous_joints) a long time ago. I also made a branch (continuous_joints_mklingen) which accomplishes the same thing. I have done a couple of tests on this, and it seems to more or less work, but I need some more rigorous tests before submitting a PR.

**Comment by mkoval** [comment]
@mklingen implemented this in #36.
