### ISSUE TITLE
Group all RealVectorStateSpaces together to improve performance

### ISSUE THREAD

**Issue by mkoval** [personalrobotics/or_ompl#39]
In #36 we switched away from a single `RealVectorStateSpace` to a `CompoundStateSpace` to support continuous joints. @cdellin pointed out that this introduces a considerable amount of overhead and @mklingen found that the overhead causes a significant performance degradation on the RRT.

We should group all of the `RealVectorStateSpaces` together to improve performance when planning with non-continuous joints.

**Comment by mklingen** [comment]
One thing I'm concerned about is keeping the order intact while also compressing as many DOFs as possible into a single state space. If we have a robot that has `continuous->limited->continuous->limited->...` for instance it should be merged into a single `RealVectorStateSpace` plus some number of `SO2` state spaces, but I need to be careful to keep the order intact. Shouldn't be too difficult.

**Comment by mklingen** [comment]
try this one https://github.com/personalrobotics/or_ompl/pull/40
