### ISSUE TITLE
Remove CO_ActiveDOFs application from or_ompl

### ISSUE THREAD

**Issue by cdellin** [personalrobotics/or_ompl#61]
`or_ompl` currently sets the `OpenRAVE::CO_ActiveDOFs` flag on the environment's collision checker before proceeding with motion planning. @mkoval and I agreed that this probably belongs in the user's code, not in the planner itself. We should remove it.

**Comment by psigen** [comment]
Can we also put a note in the `README.md` that this is a thing that one might want to do? Otherwise I'm pretty sure the average user is not going to have any idea that it could, much less should, be done.
