### ISSUE TITLE
openrave resource not found

### ISSUE THREAD

**Issue by mudasserzahid** [personalrobotics/or_ompl#62]
Hi 'em facing problem in python code, from this line
`import openravepy as rave`
'em unable to solve openrave issue can you help me , i found a lot for this issue but there is not a valid solution
'em using 
ubuntu
Gazebo as simulator
ROS-indigo
running code in catkin_ws

**Comment by psigen** [comment]
`or_ompl` is a plugin _for OpenRAVE_ (http://openrave.org/docs/latest_stable/), and OpenRAVE's python bindings are named `openravepy`.

If you are having a problem with the line `import openravepy as rave`, you are probably having an issue with your installation of OpenRAVE and not `or_ompl`.  Either OpenRAVE has not been built or installed with its Python bindings or for some reason it is not available on your `PYTHONPATH` when you are trying to use `or_ompl`.

You can check https://github.com/personalrobotics/or_ompl#dependencies for more details about the requirements of `or_ompl`.

However, if you cannot run `import openravepy`, you should probably post to the OpenRAVE Users mailing list (https://lists.sourceforge.net/lists/listinfo/openrave-users).  This issue tracker is primarily for `or_ompl` related issues.

Feel free to reopen this issue if you get to the point where OpenRAVE is loading but you are unable to use the `or_ompl` plugin.
