### ISSUE TITLE
Using or_ompl to move a robot's base

### ISSUE THREAD

**Issue by DanielMolina** [personalrobotics/or_ompl#76]
Hello,

I've been successful in installing or_ompl and I've been able to use the plugin to move a robot's manipulator. However, whenever I try to use it to move the robot's base I get an error. Thus, I was wondering if or_ompl can be used for navigation planning?

Thanks!

**Comment by DanielMolina** [comment]
No affine DOF support. Didn't initially see this.

**Comment by mkoval** [comment]
Yes, that's correct. Planning for the robot's base requires affine DOF support, which is not currently implemented. It should be relatively straightforward to implement this feature if anyone has cycles and is interested in doing so.
